### ISSUE TITLE
Concurrent user limit

### ISSUE THREAD

**Issue by Majid-Mahzarnia** [morazow/docker-outline-shadowsocks-server#2]
Hello
Thank you for this simple and useful code.
How to limit concurrent users?
Thanks

**Comment by morazow** [comment]
Hey, 
thanks for the feedback and question!

Unfortunately, it is not possible with this shadowsocks server. Multiple users concurrently can join the provided port.

I think you can maybe use https://github.com/Jigsaw-Code/outline-server, and limit the data per access key.

**Comment by Majid-Mahzarnia** [comment]
Thanks
